// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      uglify: {
        options: {
          banner: '/*! <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
        },
        build: {
          src: 'public/javascripts/<%= pkg.name %>.js',
          dest: 'public/javascripts/<%= pkg.name %>.min.js'
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-uglify');
    return grunt.registerTask('default', ['uglify']);
  };

}).call(this);
